language: ruby
rvm:
  - 2.3.1
notifications:
  slack:
    secure: DJF6UAzqDGN5tsgkU/zPqZjJVudJE9/aLHwwYXwLPbGPSw7ePpLaO4gTk6Z3GX/LxY4iGjMjqiEKkNhoxT9POPebYqduOoj5UG4PgPxve4XgQu8yS78weHfyfbYSr3KaoZgb5ZO/seY1+pTorfpTHOmPK8TOUIPBHzVHGvqdZ70LWxpsjvJi/DWOG/biy1pligGTyC7gbviNrXjfG4LXFN3HP4XXvDILLAUlUqTIFbLL2B2MZZ3+mepnOiRAKYMwtJXbX4rlG0fQmGUx0v5njPA0QLKerByedxP5NDS0w/GMjzco/LT0fjH8nbzr3au6ZQq/Jyk2y1o3Uy1efStnGJYuwXm20o0KIYmeflcr7OuQyEoLryAH9d8GLy3Wyngkm0rqrgybEJRSmNm5HIAdFR/9yQGfwKT4yiR9GdslTquJZP8k/fBJju4OYzixwb7aZgAfkfd3OyDGPX0imrDUCEBaMgYXZ9+a9nysL/Oh6n/53fe2V4oxGNCgr/OOqmx1A2xOaGBxP8IlzMUlD8HW6bYf0CbjmrvT0pXaYCgYnwwA4jvnm9NqlJ5fDXPZx6b/XRl7ZnA++bBvL5sA/suLgGDm3lYHfTHAerCbvAgtmBqjEmZxRfGuXYh0MzAbdok8h/yzOtGNB7RQoDg6nDfNYeGF6iTz+vdTX1shQkWUr7A=
