# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43202e698c6446c61194eb84418f1295db51d82427f18438fbc4aa7495d2fdf9df6ad4a082102e66066137b31cec29790541e74013c68bc903ca428294ec0466

test:
  secret_key_base: 014c5d2a4daba36b96791b624b7dd6fb99a7e671066a7642f305a99b05b4eb26880671913d09eb4328ee6c74079f26790db968cac21bb3aedd608a82116f7791

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:  <%= ENV["DALESLAB_SECRET_KEY_BASE"] %> #apparently including it here is bad...but wouldn't someone have to pwn the server??
